# Generated by Django 3.2.4 on 2021-07-17 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0011_messagemodel_threadmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagemodel',
            old_name='reciever_user',
            new_name='receiver_user',
        ),
        migrations.RenameField(
            model_name='threadmodel',
            old_name='reciever',
            new_name='receiver',
        ),
    ]
