# Generated by Django 3.2.4 on 2021-07-19 19:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0020_auto_20210719_1910'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={},
        ),
        migrations.RemoveField(
            model_name='comment',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='post',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
