# Generated by Django 3.2.4 on 2021-07-20 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('social', '0023_auto_20210720_0834'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
